ARG BASE_IMAGE=odris-jetson-humble:base
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

#WORKDIR /workspace

# change the locale from POSIX to UTF-8
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
	ros-humble-isaac-ros-cumotion \
	ros-humble-isaac-ros-cumotion-examples \
    && rm -rf /var/lib/apt/lists/*


